name: Deploy Module - Azure Container Apps

on: 
  push:
  pull_request:
    paths:
      - './modules/azure-container-app/**'

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to verify'
        type: environment
        required: true
      location:
        description: 'Region for deployment'
        type: choice
        default: 'norwayeast'
        required: true
        options:
        - norwayeast
        - northeurope
        - eastus

env:
  environment: Dev
  location: norwayeast

permissions:
      id-token: write
      contents: read
      
jobs: 
  Lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint code
        run: |
          az bicep build --file ./modules/azure-container-app/Example/main.bicep

  Validate:
    runs-on: ubuntu-latest
    needs: Lint
    environment: Dev
    steps:
      - uses: actions/checkout@v2
      
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run preflight validation'
        uses: azure/arm-deploy@v1
        with: 
          scope: subscription
          region: norwayeast
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          deploymentName: ${{ github.run_number }}         
          template: ./modules/azure-container-app/Example/main.bicep
          parameters: ./modules/azure-container-app/Example/azuredeploy.Dev.parameters.json env=dev
          deploymentMode: Validate

  What-if:
    runs-on: ubuntu-latest
    needs: Validate
    environment: Dev
    steps:
      - uses: actions/checkout@v2
      
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: 'Run what-if'
        id: what-if
        uses: azure/cli@v1      
        with: 
          inlineScript: |
            az deployment sub what-if --location norwayeast \
              --name ${{ github.run_number }} \
              --template-file ./modules/azure-container-app/Example/main.bicep \
              --parameters ./modules/azure-container-app/Example/azuredeploy.Dev.parameters.json env=Dev
              
      - name: add-what-if-to-comment
        uses: actions/github-script@v3
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = 'Results of what-if: \'
            {{ steps.what-if.outputs.stdout }};
            
            github.issues.createComment({
              issue_number; context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

  Deploy:
    runs-on: ubuntu-latest
    needs: What-if
    environment: ${{ github.event.inputs.environment }}
    steps:
    - uses: actions/checkout@v2
    
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: 'Deploy Module Azure Container Apps'
      uses: azure/cli@v1      
      with:
        inlineScript: |
          az bicep publish --file ./modules/azure-container-app/container-environment.bicep --target br:${{ secrets.BICEP_MODULE_REGISTRY }}.azurecr.io/bicep/modules/aca-environment:0.1 \
          az bicep publish --file ./modules/azure-container-app/container-app.bicep --target br:${{ secrets.BICEP_MODULE_REGISTRY }}.azurecr.io/bicep/modules/aca-app:0.1
